/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_appsync_graphqlEndpoint:
    'https://77osspmp6bdqvowxmngr5ca52y.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_cognito_identity_pool_id:
    'us-east-1:b98a9a54-5308-4c16-97de-b0aa74b6089e',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_fVR6d5Aey',
  aws_user_pools_web_client_id: '2adm31udsp94ru4lcpdodgn5oi',
  oauth: {},
  aws_user_files_s3_bucket:
    'kinderfoosv1b3ed43e47681437cacee1bec86c72090100617-dev',
  aws_user_files_s3_bucket_region: 'us-east-1',
}

export default awsmobile
